import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/contexts/ThemeProvider";
import SupabaseProvider from "./providers/SupabaseProvider";
import UserProvider from "./providers/UserProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (  
      <html lang="en">
        <body className={inter.className}>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <SupabaseProvider>
                <UserProvider>
                  {children}
                </UserProvider>
              </SupabaseProvider>
            </ThemeProvider>
        </body>
      </html>

  );
}
